routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('orders.index');
});

Route::resource('orders', 'OrdersController');
Route::get('/product/{id}', 'OrdersController@getProduct');
Route::resource('products', 'ProductsController');

app/Order_items.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order_items extends Model
{
    protected $table = 'order_items';

    protected $fillable = [
        'order_id','product_id','quantity','total'
    ];

    public function order(){
        return $this->belongsTo(Orders::class, 'order_id');
    }

    public function product(){
        return $this->belongsTo(Products::class, 'product_id');
    }
}

app/Orders.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Orders extends Model
{

    protected $table = 'orders';

    protected $fillable = [
        'total'
    ];

    public function orderItems(){
        return $this->hasMany(Order_items::class, 'order_id');
    }
}

app/Products.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Products extends Model
{
    protected $table = 'products';

    protected $fillable = [
        'name','sku','price'
    ];

    public function orderItem(){
        return $this->hasMany('App\Models\Order_items');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/OrdersController.php
<?php

namespace App\Http\Controllers;

use App\Orders;
use App\Products;
use App\Order_items;
use Illuminate\Http\Request;
use DB;
use DataTables;
use OrderItems;

class OrdersController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Orders::all();
             return Datatables::of($data)
                    ->editColumn('orderItems', function($datas){
                        return $datas->orderItems->count();
                     })
                    ->addIndexColumn()
                    ->addColumn('btn', 'orders.opciones')
                    ->rawColumns(['btn'])
                    ->toJson();
         }
        return view('orders.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $product = Products::all();
        return view('orders.create',compact('product'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            DB::beginTransaction();

            $order = new Orders($request->all());
                $order->total = $request->get('total');
            $order->save();

            $idproduct = $request->get('productos_idcompras');
            $quantity = $request->get('quantity');
            $price = $request->get('price');
            $cont = 0;

            while ($cont < count($idproduct)) {
                $details = new Order_items();
                $details->order_id = $order->id;
                $details->product_id  = $idproduct[$cont];
                $details->quantity = $quantity[$cont];
                $details->total = $price[$cont]*$quantity[$cont];

                $details->save();
                $cont = $cont+1;
            }
            DB::commit();
        alert()->success('La compra ha sido realizada.', 'Compra agregada');
        } catch (Exception $e) {
            DB::rollback();
        }
        return redirect()->route('orders.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Orders  $orders
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = Orders::find($id);
        return view('orders.mostrar', compact('order'));
    }

    public function getProduct($id)
    {
        if (request()->ajax()) {
            return Products::findOrFail($id);
        }
        return back();
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Products;
use Illuminate\Http\Request;
use DataTables;

class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Products::all();
             return Datatables::of($data)
                    ->addIndexColumn()
                    ->addColumn('btn', 'products.opciones')
                    ->rawColumns(['btn'])
                    ->toJson();
         }
        return view('products.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'sku' => 'required',
            'price' => 'required'
            ]
        );
    Products::create($request->all());

    alert()->success('El producto ha sido creado correctamente.', 'Producto creado');
    return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Products  $products
     * @return \Illuminate\Http\Response
     */
    public function show(Products $products)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Products  $products
     * @return \Illuminate\Http\Response
     */
    public function edit(Products $products)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Products  $products
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Products $products, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'sku' => 'required',
            'price' => 'required'
            ]
        );
        $product = Products::find($id)->update($request->except(['_method', '_token']));
        alert()->info('El producto ha sido actualizado correctamente.', 'Producto actualizado');
        return redirect()->route('products.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Products  $products
     * @return \Illuminate\Http\Response
     */
    public function destroy(Products $products)
    {
        //
    }
}

resources/views/includes/panel/footer.blade.php
<footer class="footer pt-0">
    <div class="row align-items-center justify-content-lg-between">
      <div class="col-lg-12">
        <div class="copyright text-center text-lg-left text-muted">
          &copy; 2019 <a href="https://www.creative-tim.com" class="font-weight-bold ml-1" target="_blank">Creative Tim</a>
        </div>
      </div>
    </div>
  </footer>

resources/views/includes/panel/menu.blade.php
<div class="mobile-menu md:hidden">
    <div class="mobile-menu-bar">
        <a href="/" class="flex mr-auto">
            <img class="w-6" src="{{ asset('images/logo.svg')}}">
        </a>
        <a href="javascript:;" id="mobile-menu-toggler"> <i data-feather="bar-chart-2" class="w-8 h-8 text-white transform -rotate-90"></i> </a>
    </div>
    <ul class="border-t border-theme-24 py-5 hidden">
        <li>
            <a href="/" class="{{ (request()->is('/')) || (request()->is('orders/*')) ? 'menu menu--active' : 'menu' }}">
                <div class="menu__icon"> <i data-feather="home"></i> </div>
                <div class="menu__title"> Ordenes </div>
            </a>
        </li>
        <li>
            <a href="/products" class="{{ (request()->is('products')) ? 'menu menu--active' : 'menu' }}">
                <div class="menu__icon"> <i data-feather="inbox"></i> </div>
                <div class="menu__title"> Productos </div>
            </a>
        </li>
        <li class="menu__devider my-6"></li>
    </ul>
</div>
<!-- END: Mobile Menu -->
<div class="flex">
    <!-- BEGIN: Side Menu -->
    <nav class="side-nav">
        <a href="/" class="intro-x flex items-center pl-5 pt-4">
            <img alt="Siap" class="w-6" src="{{ asset('images/logo.svg')}}">
            <span class="hidden xl:block text-white text-lg ml-3"> SI<span class="font-medium">AP</span> </span>
        </a>
        <div class="side-nav__devider my-6"></div>
        <ul>
            <li>
                <a href="/" class="{{ (request()->is('/')) || (request()->is('orders/*')) ? 'side-menu side-menu--active' : 'side-menu' }}">
                    <div class="side-menu__icon"> <i data-feather="home"></i> </div>
                    <div class="side-menu__title"> Ordenes </div>
                </a>
            </li>
            <li>
                <a href="/products" class="{{ (request()->is('products')) ? 'side-menu side-menu--active' : 'side-menu' }}">
                    <div class="side-menu__icon"> <i data-feather="credit-card"></i> </div>
                    <div class="side-menu__title"> Productos </div>
                </a>
            </li>
            <li class="side-nav__devider my-6"></li>
        </ul>
    </nav>

resources/views/orders/create.blade.php
@extends('panel')
@section('title', 'Crear orden')
@section('content')
<div>
    <div class="flex items-center px-5 py-5 sm:py-3 border-b border-gray-200">
    <h2 class="font-medium text-base mr-auto">
       Crear nueva orden
    </h2>
</div>
{!! Form::open(['route' => 'orders.store']) !!}
<div class="p-5 grid grid-cols-12 gap-4 row-gap-3">
    <div class="rounded-md flex items-center col-span-12 px-5 py-3 mb-2 bg-theme-5 text-gray-700"> <i data-feather="shopping-cart" class="w-6 h-6 mr-2"></i> Datos de la orden </div>
    <div class="col-span-12 sm:col-span-6 @if ($errors->has('product_id')) has-error @endif">
        <label class="font-medium text-base mr-auto">Nombre del Producto</label>
        <div class="mt-2">
             <select class="select2 w-full" id="productos_idcompras" name="product_id">
             	    <option value="">Selecciona un producto</option>
                @foreach($product as $products)
                	<option value="{{$products->id}}">{{$products->name}}</option>
                @endforeach

            </select>
        </div>
    </div>
    <div class="col-span-12 sm:col-span-6"><br><br>
    	<a class="button bg-theme-32 text-white" data-toggle="modal" data-target="#crear_productos">Agregar Productos</a>

    </div>
    <div class="col-span-12 sm:col-span-12">
    </div>
    <div class="col-span-12 sm:col-span-4 @if ($errors->has('precioproducto')) has-error @endif">
        <label class="font-medium text-base mr-auto" for="precioproducto">Precio</label>
        <input type="text" class="input w-full border mt-2 flex-1" name="precioproducto" id="price_product" min="1" value="{{old('precioproducto')}}" aria-describedby="helpPrecio" disabled>
        <span id="helpPrecio" class="help-block">
            @if ($errors->has('precio'))
                @foreach($errors->get('precio') as $message)
                    @if(!$loop->first) / @endif
                    {{ $message }}
                @endforeach
            @endif
        </span>
    </div>
    <div class="col-span-12 sm:col-span-4 @if ($errors->has('cantidad')) has-error @endif">
        <label class="font-medium text-base mr-auto" for="cantidad">Cantidad</label>
        <input type="number" class="input w-full border mt-2 flex-1" name="cantidad" id="cantidad" value="{{old('cantidad')}}" min="1" aria-describedby="helpCantidad">
        <span id="helpCantidad" class="help-block">
            @if ($errors->has('cantidad'))
                @foreach($errors->get('cantidad') as $message)
                    @if(!$loop->first) / @endif
                    {{ $message }}
                @endforeach
            @endif
        </span>
    </div>
     <div class="col-span-12 sm:col-span-4"><br><br>
    	<a class="button bg-theme-9 text-white" id="btn_add">Agregar Productos</a>
    </div>
    <div class="col-span-12 sm:col-span-12">
    </div>
    <br>
    <div class="col-span-12 sm:col-span-12">
	    <div class="overflow-x-auto">
		    <table class="table" id="details">
		        <thead>
		             <tr class="bg-gray-700 text-white" >
		                 <th class="border-b-2 whitespace-no-wrap">Opciones</th>
		                 <th class="border-b-2 whitespace-no-wrap">Producto</th>
                         <th class="border-b-2 whitespace-no-wrap">Precio</th>
		                 <th class="border-b-2 whitespace-no-wrap">Cantidad</th>
		                 <th class="border-b-2 whitespace-no-wrap">Subtotal</th>
		             </tr>
		         </thead>
		        <tfoot>
					<th colspan="3"></th>
					<th>Total</th>
					<th><h4 id="total">$. 0.00</h4><input type="hidden" name="total" id="total_re"></input></th>
				</tfoot>
		         <tbody>


		         </tbody>
		     </table>
	 	</div>
	</div>

<div class="px-5 py-3 text-right border-t border-gray-200" id="save">
    <button onclick="window.location.href='/'" type="button" class="button w-20 border text-gray-700 mr-1">Regresar</button>
    <button class="button w-20 bg-theme-1 text-white" id="submit">Crear</button>
</div>
</div>

{!! Form::close()!!}
@endsection

@section('scripts_ready')
<script type="text/javascript">
    $(function() {
        $("#productos_idcompras").on('change', onSelectproductChanges);
    });

    function onSelectproductChanges() {
		var product_id = $(this).val();
		$.get('/product/'+product_id, function (data){
			$('#price_product').val(data.price);
		});
	}

    $(document).ready(function(){
		$("#btn_add").click(function(){
			agregar();
		});
	});

    var cont = 0;
	total = 0;
	subtotal=[];
	$("#save").hide();
	$("#proveedor_id").change(showValues);

	function showValues() {
		dataProduct = document.getElementById('productos_idcompras').value.split('_');
		$("#precioproducto").val(dataProduct[1]);
	}

	function agregar() {
		dataProduct = document.getElementById('productos_idcompras').value.split('_');
		$("#precioproducto").val(dataProduct[1]);

		productos_idcompras = dataProduct[0];
		product = $("#productos_idcompras option:selected").text();
		quantity = $("#cantidad").val();
		price = $("#price_product").val();

		if (productos_idcompras!="" && quantity!="" && quantity > 0  && price!="")
		{
			subtotal[cont] = (quantity*price);
			total=total + subtotal[cont];
			var fila = '<tr class="selected" id="fila'+cont+'"><td><button type="button" class="btn btn-raised btn-warning btn-xs" onclick="eliminar('+cont+');">x</button></td><td><input type="hidden" name="productos_idcompras[]" value="'+productos_idcompras+'">'+product+'</td><td><input type="hidden" name="price[]" class="field" value="'+price+'">'+price+'</td><td><input type="hidden" name="quantity[]" class="field" value="'+quantity+'">'+quantity+'</td><td class="field">'+subtotal[cont]+'</td></tr>';
			cont++;
			evaluate();
			clean();
			$('#total').html("$ " + total);
			$('#total_re').val(total);
			$('#details').append(fila);
		}else {
			alert('Error al ingresar el detalle de la requisición, revise los datos del producto');
		}

	}

	function clean() {
		$("#cantidad").val("");
		$("#price_product").val("");
	}

	function evaluate() {
		if (total>0) {
			$("#save").show();

		}else {
			$("#save").hide();
		}
	}

	function eliminar(index) {
		total = total-subtotal[index];
		$("#total").html("$ " +total);
		$("#total_sale").val(total);
		$("#fila" + index).remove();
		evaluate();
	}
</script>

@endsection

resources/views/orders/index.blade.php
@extends('panel')
@section('title', 'Ordenes')
@section('content')
<style type="text/css">
 .table {
    width: 100%;
    text-align: center;
}
</style>
<div class="intro-y flex flex-col sm:flex-row items-center mt-8">
    <h2 class="text-lg font-medium mr-auto">
        Ordenes creadas
    </h2>
    <div class="w-full sm:w-auto flex mt-4 sm:mt-0">
        <a class="button text-white bg-theme-1 shadow-md mr-2" href="{{ route('orders.create') }}" >Crear nueva orden</a>

    </div>
</div><br>
<!-- BEGIN: Datatable -->
<div class="intro-y datatable-wrapper overflow-x-auto">
    <table class="table table-report table-report--bordered display datatable w-full">
        <thead>
            <tr>
                <th class="border-b-2 whitespace-no-wrap">Id</th>
                <th class="border-b-2 text-center whitespace-no-wrap">Productos vendidos</th>
                <th class="border-b-2 text-center whitespace-no-wrap">Total</th>
                <th class="border-b-2 text-center whitespace-no-wrap">Opciones</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>
<!-- END: Datatable -->
@endsection
@section('scripts_ready')
<script type="text/javascript">
    $(function () {
      $('#DataTables_Table_0').DataTable().destroy();
      var table = $('#DataTables_Table_0').DataTable({
          processing: true,
          serverSide: true,
        ajax: "{{ route('orders.index') }}",
        columns: [
            {data: 'id', name: 'id'},
            {data: 'orderItems', name: 'orderItems'},
            {data: 'total', name: 'total'},
            {data: 'btn', name: 'btn'},
        ],
            "language": {
                "info": "_TOTAL_ registros",
                "search": "Buscar",
                "paginate": {
                    "next": "Siguiente",
                    "previous": "Anterior",
                },
                "lengthMenu": 'Mostrar <select >'+
                            '<option value="10">10</option>'+
                            '<option value="30">30</option>'+
                            '<option value="-1">Todos</option>'+
                            '</select> registros',
                "loadingRecords": "Cargando...",
                "processing": "Procesando...",
                "emptyTable": "No hay datos",
                "zeroRecords": "No hay coincidencias",
                "infoEmpty": "",
                "infoFiltered": ""
            }
    });
  });
</script>
@endsection

resources/views/orders/mostrar.blade.php
@extends('panel')
@section('title', 'Ver compra')
@section('content')
<div>
    <div class="flex items-center px-5 py-5 sm:py-3 border-b border-gray-200">
    <h2 class="font-medium text-base mr-auto">
       Orden No. {{$order->id}}
    </h2>
</div>

<div class="p-5 grid grid-cols-12 gap-4 row-gap-3">
    <div class="col-span-12 sm:col-span-12">
    </div>
    <div class="rounded-md flex items-center col-span-12 px-5 py-3 mb-2 bg-theme-5 text-gray-700"> <i data-feather="user" class="w-6 h-6 mr-2"></i> Datos de la orden </div>
     <div class="col-span-12 sm:col-span-12">
    </div>
    <div class="col-span-12 sm:col-span-12">
        <div class="overflow-x-auto">
            <table class="table" id="details">
                <thead>
                     <tr class="bg-gray-700 text-white" >
                         <th class="text-center border-b whitespace-no-wrap">id</th>
                         <th class="text-center border-b whitespace-no-wrap">Fecha de creacion</th>
                         <th class="text-center border-b whitespace-no-wrap">Producto</th>
                         <th class="text-center border-b whitespace-no-wrap">Cantidad</th>
                         <th class="text-center border-b whitespace-no-wrap">Precio</th>
                         <th class="text-center border-b whitespace-no-wrap">Subtotal</th>
                     </tr>
                 </thead>
                 <tfoot>
                    <th colspan="4"></th>
                    <th>Total Final</th>
                    <th><strong>$ {{ number_format($order->total, 2)}}</strong></th>
                </tfoot>
                 <tbody>
                    @foreach($order->orderItems as $detail)
                        <tr>
                            <td class="text-center border-b">{{ $detail->id}}</td>
                            <td class="text-center border-b">{{ $detail->created_at}}</td>
                            <td class="text-center border-b">{{ $detail->product->name}}</td>
                            <td class="text-center border-b">{{ $detail->quantity }}</td>
                            <td class="text-center border-b">{{ number_format($detail->product->price, 2)}}</td>
                            <td class="text-center border-b">{{ number_format($detail->total, 2)}}</td>
                        </tr>
                    @endforeach
                 </tbody>
             </table>
        </div>
    </div>
    <div class="px-5 py-3 text-right border-t border-gray-200">
        <a href="/" class="button w-32 mr-2 mb-2 flex items-center justify-center border text-gray-700"> <i data-feather="hard-drive" class="w-4 h-4 mr-2"></i> Regresar</a>
    </div>
@endsection

resources/views/orders/opciones.blade.php
<div class="flex justify-center items-center">
    <a class="flex items-center text-theme-3" href="{{ route('orders.show', $id) }}" <i data-feather="check-square" class="w-4 h-4 mr-1"></i> mostrar </a>

</div>

resources/views/panel.blade.php
<!DOCTYPE html>

<html lang="en">
    <!-- Inicio del Head -->
    <head>
        <meta charset="utf-8">
        <link href="{{ asset('images/logo.svg')}}" rel="shortcut icon">
        <title>Prueba | @yield('title')</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Sitio de prueba.">
        <meta name="author" content="Jimmy Frias">
        <!-- Inicio del CSS de la pagina-->
        <link rel="stylesheet" href="{{ asset('css/app.css')}}" />
        <!-- Finalización del CSS de la pagina-->
    </head>
    <!-- Finalización del Head -->
    <body class="app">
        <!-- Inicio del Menu -->
        @include('includes.panel.menu')
        <!-- Finalización del Menu -->
            <!-- Incio del contenedor -->
            <div class="content">
                    @if (count($errors) > 0)
                        <div class="alert alert-danger">
                            <p>Corrige los siguientes errores:</p>
                            <ul>
                                @foreach ($errors->all() as $message)
                                    <li>{{ $message }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                @section('content')
                @show

            </div>
            <!-- Finalización del contenedor -->
        <!-- Incio del JS Assets-->

        <script src="{{ asset('js/app.js')}}"></script>
        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

        @section('scripts_ready')
        @show
        @include('sweet::alert')
        <!-- Finalización: JS Assets-->
    </body>
</html>

resources/views/products/create.blade.php
<div class="modal" id="crear_producto">
    <div class="modal__content modal__content--xl">
        <div class="flex items-center px-5 py-5 sm:py-3 border-b border-gray-200">
            <h2 class="font-medium text-base mr-auto">
                Crear nuevo producto
            </h2>
        </div>
        <form method="POST" action="{{ route('products.store') }}"  role="form">
            {{ csrf_field() }}
            <div class="p-5 grid grid-cols-12 gap-4 row-gap-3">
                <div class="col-span-12 sm:col-span-4 @if ($errors->has('name')) has-error @endif">
                    <label class="font-medium text-base mr-auto" for="name">Nombre:</label>
                    <input type="text" class="input w-full border mt-2 flex-1" name="name" id="name" aria-describedby="helpName" required>
                    <span id="helpName" class="help-block">
                        @if ($errors->has('name'))
                            @foreach($errors->get('name') as $message)
                                @if(!$loop->first) / @endif
                                {{ $message }}
                            @endforeach
                        @endif
                    </span>
                </div>
                <div class="col-span-12 sm:col-span-4 @if ($errors->has('sku')) has-error @endif">
                    <label class="font-medium text-base mr-auto" for="sku">Sku:</label>
                    <input type="number" class="input w-full border mt-2 flex-1" min="1" name="sku" id="sku" aria-describedby="helpSku" required>
                    <span id="helpSku" class="help-block">
                        @if ($errors->has('sku'))
                            @foreach($errors->get('sku') as $message)
                                @if(!$loop->first) / @endif
                                {{ $message }}
                            @endforeach
                        @endif
                    </span>
                </div>
                <div class="col-span-12 sm:col-span-4 @if ($errors->has('price')) has-error @endif">
                    <label class="font-medium text-base mr-auto" for="price">Precio:</label>
                    <input type="number" class="input w-full border mt-2 flex-1" name="price" id="price" aria-describedby="helpPrice" required>
                    <span id="helpPrice" class="help-block">
                        @if ($errors->has('price'))
                            @foreach($errors->get('price') as $message)
                                @if(!$loop->first) / @endif
                                {{ $message }}
                            @endforeach
                        @endif
                    </span>
                </div>

                <div class="col-span-12 sm:col-span-12">
                </div>
            </div>
            <div class="px-5 py-3 text-right border-t border-gray-200">
                <button type="button" data-dismiss="modal" class="button w-20 border text-gray-700 mr-1">Cancelar</button>
                <button class="button w-20 bg-theme-1 text-white">Guardar</button>
            </div>
        {!! Form::close()!!}
    </div>
</div>

resources/views/products/index.blade.php
@extends('panel')
@section('title', 'Productos')
@section('content')
<style type="text/css">
 .table {
    width: 100%;
    text-align: center;
}
</style>
<div class="intro-y flex flex-col sm:flex-row items-center mt-8">
    <h2 class="text-lg font-medium mr-auto">
        Productos
    </h2>
    <div class="w-full sm:w-auto flex mt-4 sm:mt-0">
        <a class="button text-white bg-theme-1 shadow-md mr-2" href="javascript:;" data-toggle="modal" data-target="#crear_producto" >Crear nuevo producto</a>
        @include('products.create')

    </div>
</div><br>
<!-- BEGIN: Datatable -->
<div class="intro-y datatable-wrapper overflow-x-auto">
    <table class="table table-report table-report--bordered display datatable w-full">
        <thead>
            <tr>
                <th class="border-b-2 whitespace-no-wrap">Id</th>
                <th class="border-b-2 text-center whitespace-no-wrap">Nombre</th>
                <th class="border-b-2 text-center whitespace-no-wrap">Sku</th>
                <th class="border-b-2 text-center whitespace-no-wrap">Precio</th>
                <th class="border-b-2 text-center whitespace-no-wrap">Opciones</th>

            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>
<!-- END: Datatable -->
@endsection
@section('scripts_ready')
<script type="text/javascript">
    $(function () {
      $('#DataTables_Table_0').DataTable().destroy();
      var table = $('#DataTables_Table_0').DataTable({
          processing: true,
          serverSide: true,
        ajax: "{{ route('products.index') }}",
        columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'sku', name: 'sku'},
            {data: 'price', name: 'price'},
            {data: 'btn', name: 'btn'},
        ],
            "language": {
                "info": "_TOTAL_ registros",
                "search": "Buscar",
                "paginate": {
                    "next": "Siguiente",
                    "previous": "Anterior",
                },
                "lengthMenu": 'Mostrar <select >'+
                            '<option value="10">10</option>'+
                            '<option value="30">30</option>'+
                            '<option value="-1">Todos</option>'+
                            '</select> registros',
                "loadingRecords": "Cargando...",
                "processing": "Procesando...",
                "emptyTable": "No hay datos",
                "zeroRecords": "No hay coincidencias", 
                "infoEmpty": "",
                "infoFiltered": ""
            }
    });    
  });
</script>
@endsection

resources/views/products/opciones.blade.php
<div class="flex justify-center items-center">
    <a class="flex items-center text-theme-3" href="javascript:;" data-toggle="modal" data-target="#edit-products{{$id}}" value="{{$id}}"> <i data-feather="check-square" class="w-4 h-4 mr-1"></i> Editar </a>
    @include('products.updated')
</div>